### ISSUE TITLE
Need to add none option to preset modes.  Added pull request.

### ISSUE THREAD

**Issue by fwmartin** [thevoltagesource/LennoxiComfort#10]
I made a pull request with a change that adds a None option to the preset modes.

**Comment by thevoltagesource** [comment]
Been on vacation but I'm back now. What version are you running?  I am on 0.96.2 and adding preset_none breaks things. I also see none as an option in the preset dropdown list in the lovelace thermostat card.  I will upgrade my environment to the latest and test again.

**Comment by fwmartin** [comment]
I'm using 0.97.2.

**Comment by thevoltagesource** [comment]
As soon as I upgraded to 0.97 I saw the same issue.  I didn't put preset_none in my code during the upgrade for 0.96 as 'none' was already an option in the web interface. Guess they fixed a bug, and you did as well.  Thanks for helping keep this project up to date!

Pull request has been merged.
