### ISSUE TITLE
Platform myicomfort error

### ISSUE THREAD

**Issue by elviso33** [thevoltagesource/LennoxiComfort#11]
Dear Jacob,

I'm new to the HomeAssistant so please bear with me.  I found your work to integrate the icomfort wifi to HA.  I followed your directions and I am getting an error "Platform error climate.myicomfort - Integration 'myicomfort' not found."  I am on HA 0.103.  I wonder if something changed.

Thanks
Paul

**Comment by elviso33** [comment]
Please ignore my issue above, I had a brain fart and placed the files in the wrong location.  Thank you for your contribution!
Paul

**Comment by thevoltagesource** [comment]
Paul - I know there are HA users with multiple zones using this integration but having only a single zone I haven't tried implementing it myself.  I believe you would just need to create put two entries in your config like this:

climate:
  - platform: myicomfort
    name: mainhouse
    username: !secret icomfort_username
    password: !secret icomfort_password
    zone: 0
    min_temp: 62
    max_temp: 87
  - platform: myicomfort
    name: mancave
    username: !secret icomfort_username
    password: !secret icomfort_password
    zone: 1
    min_temp: 62
    max_temp: 87

This passed config check for me. If this doesn't work, there are a couple of people I think I could tag in an HA forum post that could provide some insight.

**Comment by elviso33** [comment]
Dear Jacob,
That totally worked.  I should have tried few more options.  I only tried to add a second "climate" which failed.  Then I tried to add one more instance of zone and that didn't work either.  But the second platform: myicomfort was it.  I've been pissed at lennox for not giving me an option to use google or alexa but now I have a path to getting voice commands to work thanks to you.  Huge thank you for your help.
Paul

**Comment by thevoltagesource** [comment]
Wanting to automate the fan setting on this thermostat is what started me down the home automation road.  Working around the limitations and irritants of the thermostat is what got me writing software and building hardware.  It has been a great learning experience and I'm glad others can benefit from it as well. 

If you ever run into an issue with this integration or an HA update breaks it, please feel free to open an issue here or tag me (@tvs) in a message on the HA forums. I'm usually a version or two behind with HA so I'm not the first to notice.

Enjoy!
