### ISSUE TITLE
Not working with Alexa over HA Cloud

### ISSUE THREAD

**Issue by jmesberg** [thevoltagesource/LennoxiComfort#15]
I’ve been using this to control my Lennox iComfort thermostat for a few years and it works very well. Today I decided to try seeing if I could get it to work with Alexa. I exposed the climate.lennox  entity to Alexa using the HA Cloud UI, and I redid Alexa device discovery. All seemed to work well, but when I try to use the voice control I (Alexa, set temperature to x) I get this response “auto is keeping the temperature around 69 and between 65 and 85.” 

This is an accurate ‘read’ of the current settings, so I know we’ve got communication established....but all it can seem to do is to read back the current temperature, not change anything. Do you have any suggestions, or is this just not going to work with your current component?

**Comment by thevoltagesource** [comment]
It sounds like Alexa doesn't work with auto mode.  If you switch to the mode to heat or cool does the temperature control work?

**Comment by jmesberg** [comment]
That worked! Thank you very much.
