### ISSUE TITLE
ClimateDevice is deprecated, modify LennoxClimate to extend ClimateEntity

### ISSUE THREAD

**Issue by bigverm23** [thevoltagesource/LennoxiComfort#16]
as of 0.110

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:547
Integration: Climate (documentation, issues)
First occurred: 3:32:27 PM (1 occurrences)
Last logged: 3:32:27 PM

**Comment by thevoltagesource** [comment]
I haven't looked into the changes in 0.110 yet but I will and get the integration updated to fit the new standard

**Comment by thevoltagesource** [comment]
Thank you to @aicarmic for stepping in and updating and testing the code. @bigverm23 please confirm that everything is working for you now and the deprecation warning is gone.

**Comment by thevoltagesource** [comment]
The change has been confirmed to resolve the issue.
