### ISSUE TITLE
ClimateDevice is deprecated

### ISSUE THREAD

**Issue by manonstreet** [thevoltagesource/LennoxiComfort#18]
After upgrading Home Assistant to version .110, I receive the following in the error upon startup:
`ClimateDevice is deprecated, modify LennoxClimate to extend ClimateEntity`

Is it possible to get this add-on ported using [ClimateEntity](https://developers.home-assistant.io/docs/core/entity/climate)?

Thanks for creating, I use it daily!  This is my attempt to get the code updated preemptively before ClimateDevice ceases to function.

**Comment by thevoltagesource** [comment]
Yes.  I will read up on the new design and start updating the code.

**Comment by thevoltagesource** [comment]
Thank you to @aicarmic for stepping in and updating and testing the code. @manonstreet please confirm that everything is working for you now and the depreciation warning is gone.

**Comment by manonstreet** [comment]
Confirmed, no more warning message.

Thanks @aicarmic!
