### ISSUE TITLE
Home Assistant Integration change

### ISSUE THREAD

**Issue by fwmartin** [thevoltagesource/LennoxiComfort#2]
Thank you for creating this.  This is exactly what I've needed.

Just a heads up.  I spotted this in the log:

2019-03-05 21:31:42 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change climate/lennox.py to lennox/climate.py. This will stop working soon.

**Comment by thevoltagesource** [comment]
Thank you. I read about the great migration in Paulus' blog post but I hadn't thought about the fact it impacts my code.  Since I am a few versions behind, HA hasn't been yelling at me to get my attention.  Since it isn't just me using this code any more I guess I need to quit slacking!  I will work on updating the docs and getting all the appropriate pieces in their new place.

**Comment by GoPosi** [comment]
Just confirming that 0.89.1 breaks this with the migration.  This has worked greater for my needs, so thank you.  I really appreciate your work and hope to see it updated soon!

**Comment by rberger** [comment]
Hi, I see that API has been split into the other repo. But its no longer clear how to install or update the component on Home Assistant.

I tried replacing the old `lennox.py` in `custom_components/climate/` with the new one from this repo in 'ha_component'.

I am assuming that `lennox.py` is pulling the myicomfort api from a python repo, so I removed the old `lennox_api.py` from `custom_components/climate/`

I then restart Home Assistant (on hassio) and the log is showing the trace shown below.

I'm not sure if I needed to do something else to remove the old or install the new...

Thanks for creating this and any help you may be able to offer!

```
2019-03-17 13:22:49 ERROR (SyncWorker_15) [homeassistant.loader] Error loading custom_components.climate.lennox. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate/lennox.py", line 54, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'STATE_AUTO' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)
2019-03-17 13:22:49 ERROR (SyncWorker_15) [homeassistant.loader] Unable to find platform lennox.
```

**Comment by thevoltagesource** [comment]
Good news! In between the chaos of the week I upgraded my installation to 0.89.1.  I have made the needed changes to my code to get the integration running again.  Besides the file layout change that @fwmartin mentioned, HA also moved the climate constants to a new file as @rberger noticed.  Both of these have been fixed and have been running in my installation for the last day or so.

Please let me know if you have any other issues.

**Comment by thevoltagesource** [comment]
@rberger to your question on the API, the API code is now hosted on PyPI and it is listed as a dependency in the component code.  This means you are safe to remove the lennox_api.py from your component folder.  HA will download the appropriate version of the API from PyPI the first time the component is loaded.  

Thanks for asking. I have updated the README to answer this question for others that are wondering the same thing.

**Comment by thevoltagesource** [comment]
All - Please check out the README on the repository for details on proper installation on 0.89 and beyond. The new file `climate.py` must be placed in `custom_components/myicomfort` . Please note that I changed the component name (trying to clarify that this doesn't work for all things Lennox just the one thermostat) so you will need to update your `configuration.yaml` file as well.

@rberger  - The error you posted was due to HA moving the climate constants and this is addressed in the updated code.

**Comment by sandman32** [comment]
Just providing feedback - This fixed it for me!  Greatly appreciate your work.

**Comment by fwmartin** [comment]
Works for me too.

Thank you.

**Comment by rberger** [comment]
Just wanted to say the new setup is working great for me. Thanks!
