### ISSUE TITLE
Need to add version key

### ISSUE THREAD

**Issue by krelltunez** [thevoltagesource/LennoxiComfort#23]
The latest version of HA (core-2021.3.0) is throwing the following warning:

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 1:24:17 PM (1 occurrences)
Last logged: 1:24:17 PM

No 'version' key in the manifest file for custom integration 'myicomfort'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'myicomfort'

**Comment by thevoltagesource** [comment]
The version key has been added to the manifest file.  Thanks for letting me know about the warning.
