### ISSUE TITLE
Integration fails for thermostats that support emergency heat 

### ISSUE THREAD

**Issue by klingon888** [thevoltagesource/LennoxiComfort#25]
Updated to Home Assistant 2021.4.0. Previously working but no longer working in this new HA version

`2021-04-08 11:34:03 ERROR (MainThread) [homeassistant.components.climate] Error while setting up myicomfort platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 213, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 547, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 176, in state
    return self.hvac_mode
  File "/config/custom_components/myicomfort/climate.py", line 216, in hvac_mode
    return HVAC_MODES[self._api.op_mode]`

**Comment by PeteRager** [comment]
did you get this working?  I'm also trying to get HA integrated.  Running into login problems and not sure if that's because the Lenox API changed or I'm just doing something wrong.

**Comment by thevoltagesource** [comment]
@klingon888 I looked thru the change log for 2021.4 and there is a small change to one of the methods for climate integrations.  Not sure if that is what cause the failure but I will make the appropriate updates and build a new release.

@PeteRager for this integration you have to use the same credentials you use on the myicomfort.com website.  Which for me was just a username not an email address.  

I do need some help testing these changes out.  My Lennox WiFi thermostat died last year and it is apparently discontinued.  Lennox replaced it with the S30 so I no longer have valid credentials to the myicomfort.com website.  Would either one of you want to loan me access to your account to make testing faster?

**Comment by PeteRager** [comment]
My inability to login was related to having an S30 which does not go through either of those APIs.  I’m off now extending this web scraper.  https://github.com/bmenchaca/icomfort3-scraper

This works for me and have extended to support turning fan on.  It’s slow and they don’t appear to have a clean API.

**Comment by blathers123** [comment]
@thevoltagesource 
Thanks a ton for maintaining this even though you don't have the thermostat anymore. I'm not in a position to upgrade my thermostat so this is a life saver. 

I can't give you access to my icomfort account unfortunately but I can help test however I can, let me know if/how I can help

**Comment by blathers123** [comment]
I've just updated to home assistant 2021.5.1 and this thermostat integration appears to be working fine. I'm not getting any errors in the logs as far as I can see and it looks like the integration is updating the thermostat and vise versa

@klingon888 Are you still experiencing this issue? Can you verify your internet was working correctly?

@thevoltagesource Best guess is that `self._api.op_mode` was set to `None` upon initialization and was never updated, so `HVAC_MODES[self._api.op_mode] ` threw an error. Additionally, I can't find any changes in the home assistant commit history over the past few months that would break the functionality. I have a collective 30min looking into this, with no dev experience for home assistant, so take this with a big grain of salt

**Comment by thevoltagesource** [comment]
Thank you for testing it out, I'm glad to hear it is working for you.  I saw in the release notes of 2021.4 that they changed the method name for pulling other attributes not specifically defined by a method and I didn't know if that was causing the problem. 

 I also found out while checking out another issue, that while I no longer have that thermostat my account still works. My profile remembers the thermostat and I can pull its last reported state.  So the only thing I can't do is make or receive changes.

Now I need to get my act together and upgrade HA. Thanks again.

**Comment by klingon888** [comment]
@thevoltagesource thanks for maintaining this despite no longer having the tstat.

I just updated to latest version and unfortunately still getting the following errors. On HA 2021.5.1 running on Docker. I even uninstalled and reinstalled the icomfort integration thru HACS. Same error. Not sure whats going on here since its working for @blathers123

2021-05-09 13:27:26 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform myicomfort
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 176, in state
    return self.hvac_mode
  File "/config/custom_components/myicomfort/climate.py", line 216, in hvac_mode
    return HVAC_MODES[self._api.op_mode]
IndexError: list index out of range
2021-05-09 13:27:26 ERROR (MainThread) [homeassistant.components.climate] Error while setting up myicomfort platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 239, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 176, in state
    return self.hvac_mode
  File "/config/custom_components/myicomfort/climate.py", line 216, in hvac_mode
    return HVAC_MODES[self._api.op_mode]
IndexError: list index out of range

**Comment by thevoltagesource** [comment]
@klingon888 it sounds like @blathers123 is spot on with the op_mode being in an invalid state.  Are you comfortable editing the custom component on your install to try this fix out?  The file is ```climate.py``` in your HA config folder under ```custom_components/myicomfort```. You just need to add this line:

```        self._api.op_mode = 0```

to the end of the ```__init__``` method, it should land on line 140 and will be right after the line that sets the ```max_temp``` variable. This will force the integration to report the system as off to HA util it pulls the current state from the Lennox cloud. If that fixes it for you I will try get a few other testers to check it out and make sure there are no unintended consequences to initially setting that value.

**Comment by klingon888** [comment]
Yup, definitely unintended consequence.... The integration started but it also set my tstat's Mode to OFF when I restarted HA. I then manually set my tstat's mode to Emergency Heat, waited 10 mins but the integration's Operation mode in HA not updating and still showing OFF.

I restarted HA and same thing happens... the integration resets my iComfort Mode to OFF.

Following error keeps repeating every min:

2021-05-13 09:23:39 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 176, in state
    return self.hvac_mode
  File "/config/custom_components/myicomfort/climate.py", line 217, in hvac_mode
    return HVAC_MODES[self._api.op_mode]
IndexError: list index out of range

**Comment by thevoltagesource** [comment]
My thermostat didn't have an emergency heat mode. Sounds like there is an additional mode that my integration is not handling which is causing the problem and not the HA version. I would be curious to see some of the raw output from the API wrapper. 

I am on vacation until next week but I will get you a few things to run as soon as I can to see what is coming back from the cloud.

**Comment by thevoltagesource** [comment]
If you have python3 on your local system you can install the myicomfort module and run the test locally.

Install python module: ```python3 -m pip install myicomfort```

If not, your HA container already has the module installed and you can run the commands from a prompt inside your container.  either way:

```
~/ python3
>>> from myicomfort.api import Tstat
>>> tstat = Tstat("icomfort_username", "icomfort_password")
>>> tstat.pull_status()
>>> tstat.op_mode
# <- Current Mode
```
CTRL-D will get you out of the Python environment.  My guess is that your system has other equipment attached that I didn't account for. If you can cycle thru the modes on your thermostat and get me the corresponding values returned by the API for each one I can see how they fit into the HA climate platform and get them added to the integration.

**Comment by klingon888** [comment]
You're right. Now that its warmer, I've set my HVAC to OFF mode and the integration shows no errors when I restarted HA. So its definitely missing some of the modes.

Manual modes avail:  0- Off, 1- Heat, 2- Cool, 3- Heat/Cool, 4- Emergency Heat

**Comment by thevoltagesource** [comment]
HA doesn't support a 5th mode so I am looking thru other thermostat integrations to see how they handle emergency heat mode.  I know the Honeywell integration supports it  and I am looking for one or two more to see if they handle it the same way. I'll let you know as I make progress so you can test it out.

**Comment by thevoltagesource** [comment]
The Honeywell thermostats support emergency heat mode and the integration handles this by supporting aux_heat mode.   It doesn't look too hard to implement this.  I will work on adding this to my integration and let you know when it is ready to test.

**Comment by thevoltagesource** [comment]
Doh, going thru and updating issues and I responded with essentially the same place I am at...  I see how to do it.  I will work on it. :)

**Comment by tumtumsback** [comment]
Confirmed this is broken for 2021.6.3 -- working fine for me when I rollback snapshot to 2021.5.5

Error message in 2021.6.3: "...Integration 'myicomfort' not found..."

**Comment by tumtumsback** [comment]
Also, just want to say thank you very much for this integration!!!!! It works amazingly when it works; but, I was sleeping last night @ 75 degrees wondering why I was so hot lol.

**Comment by thevoltagesource** [comment]
@klingon888, @tumtumsback - I finally got the time to figure this out.  If the thermostat is in emergency heat mode, it presents to HA as being in Heat mode with the Aux Heat turned on.  Because this is treated as an extension of the normal heating mode, when Aux Heat is turned off in HA, the integration will put the thermostat back in normal heat mode (HVAC_MODE_HEAT). 

Please let me know how it goes.

**Comment by klingon888** [comment]
> @klingon888, @tumtumsback - I finally got the time to figure this out. If the thermostat is in emergency heat mode, it presents to HA as being in Heat mode with the Aux Heat turned on. Because this is treated as an extension of the normal heating mode, when Aux Heat is turned off in HA, the integration will put the thermostat back in normal heat mode (HVAC_MODE_HEAT).
> 
> Please let me know how it goes.

I installed v3.1-beta.1 and it seems to be working. Status is updating correctly and showing as "hvac_action: heating". BTW, what does the "Aux heat" slider at the bottom of the status screen do? Thanks for continuing to update this.

![image](https://user-images.githubusercontent.com/30375535/144112555-a76de849-b262-43d0-8e87-92d40878aa59.png)

**Comment by thevoltagesource** [comment]
Aux Heat is how HA represents an auxiliary heater or emergency heat mode.  So, in the case of the Lennox thermostat, if you turn that switch on it should change your thermostat to emergency heat mode (mode 4) and if you turn it off it should set the thermostat back to normal heat mode (mode 1). The same should hold true if you change modes from the thermostat, normal heat should update HA to show operation 'Heat' with Aux heat 'off', and changing the thermostat to emergency heat should be represented in HA by the Aux heat switch flipping to 'on'.

How does the emergency heat thing work?  Is this a mode you pick when the weather gets really cold or does the HVAC system enable it as needed?

**Comment by thevoltagesource** [comment]
With you switch Aux heat on, does the temp selector disappear or just not function?

**Comment by PeteRager** [comment]
I was solving a similar issue on the S30 for HA several weeks back.  Here’s my understanding if it helps…

Systems with heat pumps that are deployed in cold climates require a back up furnace because heat pumps are not effective in low temperatures.  Internally the HVAC controller should take care of this via some configured “balance points” (eg temperatures) that indicate when the heat pump should be “locked out”.  So in practice you just set the system to heat and it takes care of the rest.  The S30 reports back aux=True when the backup furnace is running.

From the S30 panel you can set the mode to “Emergency Heat”, which causes the system to bypass the heat pump and use the furnace instead.  Since Emergency Heat is not a valid HA mode.  Emergency Heat should get  mapped to “Heat” and HA Aux=On.   Likewise turning HA Aux On should set system mode to Emergency Heat.  Turning HA aux off, I chose to revert the system to Heat as that seemed a better choice than Off. 

I also report the Lennox “aux” flag back as a custom attribute on the climate - for those who want to track when the heat pump vs backup furnace is running. 

Since the backup furnace could be running when in Heat or Emergency Heat, I don’t use the Lennox Aux flag to drive the HA aux switch.

**Comment by klingon888** [comment]
> How does the emergency heat thing work? Is this a mode you pick when the weather gets really cold or does the HVAC system enable it as needed?

The emergency mode works for HP units with backup heat e.g. gas/electric resistance. When the weather gets too cold, I can manually switch to emergency/aux mode so it only runs on gas.

**Comment by klingon888** [comment]
> With you switch Aux heat on, does the temp selector disappear or just not function?

When I switch my tstat to Aux/Emergency mode, it shows as "Heating" on my HA panel with the Target temp dial - see below. Once its in this mode, any setting that I manually change in HA panel will not get updated in my iComfort tstat (Mode, Target temp), ie. if I change Target temp to 68 using the Temp dial in my HA panel, this does not get updated in my tstat. 

![image](https://user-images.githubusercontent.com/30375535/144127077-ac4dc020-d3ce-4429-9677-655455d44793.png)

![image](https://user-images.githubusercontent.com/30375535/144127136-791032b9-24a7-4fc2-9ce1-fdd1a5d17883.png)

**Comment by thevoltagesource** [comment]
@PeteRager - Thank you for the info, you filled in the holes I had on how it works.  I handled the emergency heat mode just as you described.  I derived that solution from looking at the Honeywell climate integration and it is great to have the confirmation. 

I really like the idea of passing the aux flag back to HA to track which heater is running.  I don't know if the API for this thermostat reports that back or not.  I know my wrapper doesn't handle it since I didn't know about aux heaters back when I wrote it. Maybe I can get someone with one of these thermostats to trust me with their credentials, I would love to see what extra info is available with the emergency heat option added to the system.

@klingon888 - I figured out why the temp was not adjusting. I missed the fact that the underlying API had some logic for set points based on the mode.   Please install [v3.1-beta.2](https://github.com/thevoltagesource/LennoxiComfort/releases/tag/v3.1-beta.2) and let me know if it works better now.

**Comment by klingon888** [comment]
> @klingon888 - I figured out why the temp was not adjusting. I missed the fact that the underlying API had some logic for set points based on the mode. Please install [v3.1-beta.2](https://github.com/thevoltagesource/LennoxiComfort/releases/tag/v3.1-beta.2) and let me know if it works better now.

Status updating correctly. Changing temps also working now. TQ.

**Comment by thevoltagesource** [comment]
I just created release with these changes [v3.1.0](https://github.com/thevoltagesource/LennoxiComfort/releases/tag/v3.1.0). The update should appear in HACS soon. If you run into any problems with this, feel free to open this issue back up.
