### ISSUE TITLE
Unable to install via hacs

### ISSUE THREAD

**Issue by Joanm506** [thevoltagesource/LennoxiComfort#26]
When I try to install thru HACS, I can find it, and hit integrate and install, but nothing ever installs. I see a bit of red writing, but it flashes by very quickly and I cant read it.  I do get a HIVE Custom component showing up. I dont have any hive devices that I know of, but it does seem thermostat related, guess i will try to get it working

**Comment by thevoltagesource** [comment]
I'm not sure where the HIVE component came from. What version of HA are you running?

**Comment by thevoltagesource** [comment]
One other thing is that I haven't upgraded the integration to show up on the integrations page and be configured via the UI.  It still requires manual config in the yaml.  I did just install the integration from HACS and it started and connected.  I am still running HA 2021.1.5.  If you are on a newer version there are reports of issues that I am investigating.  Let me know what your setup is and I will be happy to help.

**Comment by Joanm506** [comment]
2021.5.1 is my core version. 
I know that nothing got installed because my custom_components folder does not have anything for the integration in it.
I did put the changes into my climate.yaml

But I just tried it again and it magically installed. So hopefully everything is ok now

**Comment by thevoltagesource** [comment]
I am closing this issue as it appears to have self resolved.  Feel free to open a new one if needed.
