### ISSUE TITLE
HomeKit control for auto mode not changing Comfort sync thermostat

### ISSUE THREAD

**Issue by PaRkThEcAr** [thevoltagesource/LennoxiComfort#28]
morning all! So when i control the thermostat with HomeKit in app, it doesnt change the status on the thermostat or Home assistant. it also does not post any details in the logs from what i see. i CAN change it if i use Siri though. i can also get the automode to change if i set it to heat, change the temp to my high temp, then set the cool temp to my low temp for auto.  here are some screens and details

the thermostat DOES receive the change here according to hass.
```send command set_temperature to TargetTemperature to 21.1°C, CoolingThresholdTemperature to 22.8°C, HeatingThresholdTemperature to 19.4°C for Thermostat```

here is what it shows in Home Assistant.
![Screen Shot 2021-05-31 at 7 30 38 AM](https://user-images.githubusercontent.com/39027440/120201313-8ac70300-c1e2-11eb-8ece-8dc7f2bbfe0a.png)

here is what i changed it too in HomeKit
![IMG_0021](https://user-images.githubusercontent.com/39027440/120201365-987c8880-c1e2-11eb-9ff9-56056b52a8dc.PNG)

I hope this makes sense :(

**Comment by PaRkThEcAr** [comment]
oh, and here is my  hass information

```arch: armv7
audio_input: None
audio_output: None
boot: true
image: homeassistant/raspberrypi4-homeassistant
ip_address: 172.30.32.1
last_version: 2021.5.5
machine: raspberrypi4
port: 8123
ssl: false
update_available: false
version: 2021.5.5
version_latest: 2021.5.5
wait_boot: 600
watchdog: true```

**Comment by thevoltagesource** [comment]
Hi @PaRkThEcAr.  It looks like the Comfort Sync thermostat you have is the equivalent of the Lennox S30/E30/M30 thermostat. Unfortunately this integration only works with the older Lennox WiFi iComfort and equivelent thermostats.  However I do have the Lennox S30 and have it working with HA via HomeKit. I am also in discussions with someone who is working on building an integration for HA to work with these newer thermostats.  You can jump over to the [S30 repository](http://github.com/thevoltagesource/LennoxS30/) if you want to keep up with any news I have on that project. If you need help getting your thermostat connected to HA via HomeKit you can email me or you can jump on to the HA community forums.

**Comment by PaRkThEcAr** [comment]
Are you sure i have an S30? because the integration works, just not with HomeKit (only partially) 
unfortuantely i dont really see a way to determine my model number either in software or on the back of the thermostat itself
![IMG_0028](https://user-images.githubusercontent.com/39027440/120390126-91d93880-c2ea-11eb-8f5e-f34574d1681a.JPG)

**Comment by thevoltagesource** [comment]
I stand corrected. I googled Confort Sync and it came up with the newer model which matches the S30 series and I was just confused. I'll blame it on not getting enough sleep over the weekend. Anyway...

**Comment by PaRkThEcAr** [comment]
So I merely added the integration with HACs then used the HomeKit bridge to bridge the accessory over. I have other HomeKit devices with HA and with native set up as well (with my Meross devices) which all work fine. The bridge is set up to "bridge" mode.

I think that answers what you were asking :) I'm just using your integration and the default HomeKit bridge in hass :) I'm not quite sure what you mean by "Apple device" though.

**Comment by thevoltagesource** [comment]
To use HomeKit you need something serving as a hub which the certain Apple devices (AppleTV, HomePod or an iPad) can do do or HA can act like a HK controller and you can connect devices directly to it. But since you are in bridge mode for HA that tells me what I need.

The version of HA you are running supports auto mode for climate devices so that isn't the problem.  You mentioned that Siri can set temps but when you try setting from the home app it doesn't work.  Does the home app work when it isn't in auto more?

On the iPhone screen where you can adjust the temp, click on the gear icon in the bottom right to bring up the device details.  if you scroll down the list, near the bottom for serial number it will list the entity ID that HA is presenting (ex climate.lennox).  Does this match the entity ID for the thermostat card in Lovelace?

**Comment by PaRkThEcAr** [comment]
Good morning! yes, i do have a HomeKit Hub. about 7 HomePods, 3 AppleTV's, and an iPad.

here is the information provided by the HomApp.
![IMG_0045](https://user-images.githubusercontent.com/39027440/120796310-e9002880-c4f7-11eb-8376-9f4281cbf74e.jpg)

here it is in Hass. 
![image](https://user-images.githubusercontent.com/39027440/120796854-8f4c2e00-c4f8-11eb-890a-60a9887d3ff1.png)

and for good measure, lovelace says the same
![image](https://user-images.githubusercontent.com/39027440/120797004-bacf1880-c4f8-11eb-92a1-eda3323ccd7a.png)



I mentioned it in the original post on the issue. but the Home App doesnt work when setting auto temps. However, i can set a Cooling temp and a Heating temp as well as Off mode. just setting temps for Auto doesnt work. 

I can kind of trick it though

if i go through and set a cooling temp to the low i set Auto, then switch to heating and set a heating temp to the high i want to set auto, then switch to auto and adjust to those temps, i can THEN set the temperature. but thats really convoluted :?. so basically, if i just want to open the home app and set the temperature with Auto, i cant do it without going through that difficult route.

**Comment by thevoltagesource** [comment]
@PaRkThEcAr I figured out what was wrong.  HomeKit sends the high and low set points along with a generated single set point when in auto mode.  My logic was based on the standard HA call that sends either the single set point or sends high/low. Having that extra data from HomeKit caused my integration to fail. I ran thru several tests and it looks to be working properly now.  Upgrade to v3.0.3 and let me know how it goes.

**Comment by PaRkThEcAr** [comment]
I see that now! i will update it and let you know! give me a moment to update and test it :)

**Comment by PaRkThEcAr** [comment]
an update:

so HomeKit control seems to work pretty great! scenes and manual control all seem to work with one exception.
As i am in a mixed media home, some of my users choose to make automations using HomeKit rather than Home assistant. at this time, all my Hubs are running the iOS 15 beta (go big or go home i guess) and automations dont seem to control the accessory. It is unclear if it is the beta causing the issue, or if it is the integration itself.

 its nothing i cant do in Home Assistant, but some of my users would prefer to make automatons there as its a bit easier for them to learn :)

**Comment by PaRkThEcAr** [comment]
and again, thanks so much for looking into this. i get i am kind of an odd case to look at, but i am glad to contribute however i can.

**Comment by thevoltagesource** [comment]
Cool.  I opened a new issue for the automation piece since this is resolved.  Mostly it helps me feel like I am accomplishing things if I can close an issue but it also helps with visibility without making others scrolls thru a different issue.

Wanting to automate some features of my thermostat is what lead me to Home Assistant and to build this integration.  I'm excited that other people found my work useful and are taking advantage of it.
