### ISSUE TITLE
Integration broken after 2021.6.3 upgrade

### ISSUE THREAD

**Issue by thevoltagesource** [thevoltagesource/LennoxiComfort#30]
Confirmed this is broken for 2021.6.3 -- working fine for me when I rollback snapshot to 2021.5.5

Error message in 2021.6.3: "...Integration 'myicomfort' not found..."

_Originally posted by @tumtumsback in https://github.com/thevoltagesource/LennoxiComfort/issues/25#issuecomment-856876414_

**Comment by thevoltagesource** [comment]
@tumtumsback I created a new issue for your report as that other one turned out to be an unsupported mode.  I should (and will) update the title of that other issue.

But to your issue, what version of the integration are you running?Starting in 2021.3 HA started logging a warning for any custom components that did not report their version in the manifest file. Then in 2021.6 HA stopped loading those components.  I added the required field in version 3.0.1 (3.0.2 is the latest) of the integration. Can you check your version and possibly reinstall it thru HACS?

**Comment by thevoltagesource** [comment]
If you have the Home Assistant Community Store (HACS) integration installed in your HA instance it makes managing custom components easier.  However, you can certainly manage it the way you previously done it by by downloading the files and putting them in the appropriate folder.  

Either way, yes if you will download the files from the [latest release](https://github.com/thevoltagesource/LennoxiComfort/releases/tag/v3.0.3) and replace the ones currently in use, the component should properly load when you restart HA.

**Comment by tumtumsback** [comment]
I do have HACS, just not sure how to find your integration via HACS.

**Comment by thevoltagesource** [comment]
You will need to delete the folder you used for the manual installation first, then from the integrations tab of HACS, click the blue ```+ Explore and Repositories``` button on the bottom right.
![image](https://user-images.githubusercontent.com/164573/121435682-f0369480-c944-11eb-8d33-c31719d079ae.png)

Then in the pop-up type ```Lennox``` and this integration will be the only result. 
![image](https://user-images.githubusercontent.com/164573/121435651-e3b23c00-c944-11eb-8c96-3f5fd735d53f.png)

Click the integration, choose install, and after a reboot you should be back to controlling your thermostat from HA.  All of the config file entries remain the same. 

3.0.3 is now the latest version.  I fixed some logic this morning to allow better HomeKit control.

**Comment by tumtumsback** [comment]
It worked -- you are amazing! Where can I 'buy you a coffee?'

**Comment by thevoltagesource** [comment]
I'm glad it is working for you again.  Let me know if you run in to issues in the future.

I really appreciate the the offer of the coffee.  However, I would ask instead that you find an opportunity to help someone in your area of influence and pay it forward.  This integration is my way of giving back to the community for all the work that is put in to the integrations I use, as well as HA itself. I find it super cool that people are using my integration.
