### ISSUE TITLE
Siri not accurately changing thermostat values.

### ISSUE THREAD

**Issue by PaRkThEcAr** [thevoltagesource/LennoxiComfort#32]
Morning! So I have an issue that's homekit related again. Here are the details

iOS 15 Siri (audioOS 15 for HomePods) when trying to change temps in a range sets the temperature to 45 on the low, then doesn't touch the high. Here is a video showing how.

With some testing using other thermostats, it seems to be an issue only here. https://user-images.githubusercontent.com/39027440/134554696-dbad702f-48cc-43ef-b6a4-f7da33f592b7.MOV

**Comment by thevoltagesource** [comment]
I finally upgraded to 15.1 (from 14.x) and HA shows the correctly updated set points when I say 'hey Siri, set the downstairs thermostat to 65 to 75' when the system is in heat/cool mode.  Was this possibly resolved in an IOS update? 

Note: Siri does not set the thermostat correctly if I give a single set point while in this mode.
