### ISSUE TITLE
Integration is throwing 'IndexError: list index out of range' Error

### ISSUE THREAD

**Issue by kwkid** [thevoltagesource/LennoxiComfort#36]
Firstly, love the integration.
Secondly, i'm getting the following error being logged numerous times during the day.

**Log:**
Error doing job: Task exception was never retrieved
6:37:07 AM – (ERROR) myicomfort (custom integration) - message first occurred at December 2, 2021, 7:20:36 PM and shows up 15 times

**Trace**
2021-12-02 15:40:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
if self.hvac_action:
File "/config/custom_components/myicomfort/climate.py", line 226, in hvac_action
return HVAC_ACTIONS[self._api.state]
IndexError: list index out of range

I can't really say when this started but the frequency of the error is increasing. It looks like self.api.state is referencing an element (HVAC_ACTIONS) that perhaps does not exist? Any assistance or help in trouble-shooting exactly what's going on would be appreciated.

**Comment by thevoltagesource** [comment]
Interesting.  I am finishing up changes to the integration this week to address an additional mode (emergency heat) I was unaware of since my system didn't have that equipment.  I wonder if this is something similar.  The states/actions my integration accounts for are Idle (state = 0), heating (state = 1), and cooling (state = 3).   To help me get a better understanding of what's going on, could you tell me what features/equipment you have in your HVAC setup (compressor, heat pump, UV light, etc)? Have you noticed what the thermostat is reporting the system is doing when this error occurs?

If you are comfortable doing some python level investigation... If you have python3 on your local system you can install the myicomfort module and run the test locally.

Install python module: `python3 -m pip install myicomfort`

If not, your HA container already has the module installed and you can run the commands from a prompt inside your container. either way:
```
~/ python3
>>> from myicomfort.api import Tstat
>>> tstat = Tstat("icomfort_username", "icomfort_password")
>>> tstat.pull_status()
>>> tstat.state
# <- Current state
```
CTRL-D will get you out of the Python environment. 

If you can find out what state value(s) the API is reporting outside of the three the integration already covers, and tell me what action that correlates to on the thermostat, I will see how I can make that fit into the HA climate platform and get them added to the integration.

I am glad this has been working for you and hopefully we can eliminate the errors.

**Comment by alindner19** [comment]
While you are under the hood, I had to make a very small change for mine.  Not related to this, but when you started mentioning states it got me thinking.  I have Circulate action and it threw errors for indexing on HVAC_ACTIONS with index 3.  I added this below and all was well with the world again.  Guess not sure how many Lennox systems have circulate as an option or if people use circulate, if you didn't you wouldn't see the error.

```
CURENT_HVAC_CIRCULATE = "circulate"
HVAC_ACTIONS = [
    CURRENT_HVAC_IDLE, CURRENT_HVAC_HEAT, CURRENT_HVAC_COOL, CURENT_HVAC_CIRCULATE,
]
```

**Comment by kwkid** [comment]
Interesting comments...thx for sharing
I run a Lennox furnace (SLP98VH070XV36B) and added in a new Lennox AC (EL18XCVS024) recently back in July 2021. As part of getting ready for winter i cut the power to the AC at the breaker panel sometime in October of this year. I didn't notice the errors back in October. I can't say for certain what the thermostat is reporting at the time of error..i guess it's either Heat or Idle.
I checked my Lennox iOS app and under Heat I have  the standard Off, Cool, Heat or Cool and Heat...Under Fan I have On, Circulate and Auto... 
So perhaps alindner19 comments will work for me.  The other option I guess is to turn the AC power back on at the breaker level to see if the error continues or not... 

thoughts?

**Comment by thevoltagesource** [comment]
Cutting power to the AC for winter is such foreign concept to someone like me that lives in SE Texas.  Heater was running last week and the AC is running today.  Gotta love Texas weather. 

@alindner19  I don't mind adding another HVAC_ACTION but I am curious what equipment you have on your system that makes this an option. Is it a humidifier or uv light? My Lennox system had a circulate option for the fan like @kwkid but not a circulate action for the whole system. Does the IOS app report circulate when the system is in this state?

@kwkid maybe it will help you as well.  I am curious if the reason you have this extra state is the same reason.

Part of the reason I dropped pursuing getting this integration merged into the official HA code base was extra modes/states are not allowed and I wanted that Fan Circulate option.  Their reasoning for the restriction is that the officially supported modes/states work with Alexa and Google integrations and items outside of that can cause issues.

**Comment by kwkid** [comment]
So i turned the breaker back on the AC to see if the error would stop. Unfortunately i did not as HA continues to report

**Error**
Logger: homeassistant
Source: custom_components/myicomfort/climate.py:226
Integration: myicomfort (documentation, issues)
First occurred: 7:41:53 AM (1 occurrences)
Last logged: 7:41:53 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
    if self.hvac_action:
  File "/config/custom_components/myicomfort/climate.py", line 226, in hvac_action
    return HVAC_ACTIONS[self._api.state]
IndexError: list index out of range
**Error End**

I then took @thevoltagesource advice and installed the mycomfort module and ran the python steps interactively...Basically returns a 0 when the thermostat is idle and is returning a 1 when Heating. The challenge now it to capture what the thermostat is doing / returning (outside of HA) when the HA throws it's error..

**Comment by alindner19** [comment]
I do have a humidifier, but the option is there to keep air flowing at a lower rate then fan on would be.  I'm not sure why is have this option when others don't, system came with the house when I bought it 3 years ago. 

 I'm in Wisconsin, so I also flip the breakers off for AC over winter.

The error shown is the same error I got, I logged the index to see what it was and just put it in there.  I then could see when it was happening, when the controller switched to circulate, not heat or ac or humidify requested.  I circulate during the day to keep air moving although I'm not sure it really does much.

**Comment by thevoltagesource** [comment]
@alindner19 your comment made a light bulb turn on for me.  I was still stuck thinking of modes and not system state. The circulate state/action is what the thermostat reports when the fan is in circulate mode, and it kicks on without the rest of the system coming on.  Part of my issue in snapping to this was when I had this thermostat (mine died and Lennox replaced it with an S30), it would show the system was circulating air but that state was not passed to the cloud API and app.  Lennox must have finally added that feature to the API. Thank you for the insight, this probably is the same issue @kwkid is experiencing.  

The easy way to address this is to add an unofficial HVAC_ACTION like you did.  But now that I understand the scope, I am weighing this against the fact that a lot of people are using this integration and this change could cause new errors for people, depending on their setup.  The person working on the S30 integration had a good idea of mapping things like this to official HA states, and then using custom attributes to pass the actual state to HA for visibility/tracking.

**Comment by kwkid** [comment]
So i've been running with the AC powered off at the breaker and i've implemented a continuous loop every 60 seconds as per @thevoltagesource instructions above...at 11:55 and 12:06 what i believe was the unknown state has appeared...see the attached screenprint (hope it becomes visable)...the state showing 3. Unfortunately i don't know what the thermostat was showing as it has since went back to Idke

![image](https://user-images.githubusercontent.com/77468155/144719998-212e712e-1b22-4a6e-939b-eef46e706bf2.png)

**Error**
2021-12-04 11:55:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
if self.hvac_action:
File "/config/custom_components/myicomfort/climate.py", line 226, in hvac_action
return HVAC_ACTIONS[self._api.state]
IndexError: list index out of range
**Error End**

The error above repeats also at 12:06

**Comment by kwkid** [comment]
Interesting how the 3 appears after the 1 in both instances

**Comment by kwkid** [comment]
Ok...it happened again...this time i was able to capture the thermostat...

**Error**
2021-12-04 14:51:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
if self.hvac_action:
File "/config/custom_components/myicomfort/climate.py", line 226, in hvac_action
return HVAC_ACTIONS[self._api.state]
IndexError: list index out of range
**Error End**

from @thevoltagesource error log implemented above the state shows: 3
![image](https://user-images.githubusercontent.com/77468155/144722957-2302dbb3-6997-4bb7-a61c-a7e21721f126.png)

from the lennox thermostat, it shows "system is waiting"....
not really sure what it's waiting for...but this eventually clears and goes to idle
![lennox](https://user-images.githubusercontent.com/77468155/144723027-8970f523-959e-43df-95aa-48b50817ed68.jpg)

**Comment by alindner19** [comment]
I think I might have been too happy to just have the error going away rather then finding the real answer.  I'm seeing now that State 3 should be Waiting and not fan state of circulate.  Why they have Waiting state is not for this integration to solve, it has it so the integration should support it.

I don't see how adding state index of 3 as waiting is something that could break other instances.  If systems do not go to waiting state a state of 3 would never be reported.

**Comment by kwkid** [comment]
I added the following lines similar to @alindner19, restarted HA and it's been over 24 hours with no errors in the logfile.

CURRENT_HVAC_WAITING = 'waiting'
HVAC_ACTIONS = [
    CURRENT_HVAC_IDLE, CURRENT_HVAC_HEAT, CURRENT_HVAC_COOL, CURRENT_HVAC_WAITING] 

@thevoltagesource do we know what the next steps are for this issue. Will assume that this maybe addressed in your upcoming release

**Comment by thevoltagesource** [comment]
I wrapped up my emergency heat support release and I will find a solution for this. I have an idea on how to handle this and keep HA happy.

@alindner19 the issue isn't with this integration breaking when talking to the system, it is with other HA integrations (HomeKit, Google, etc) breaking when a non-supported state is being reported by the climate platform for this thermostat.  

System waiting is a cool down period during which the the system is idle but it will not switch to an active state regardless of set point triggers. My experience with this state is with the system protecting the A/C compressor.  There is a minimum time required between the compressor turning off and cycling on again. If the set points would trigger the compressor on in this time frame, the thermostat would report 'System Waiting' until the cool down timer expired.  My system would also enter this state for a set period of time on power up since it did not know when the compressor had last turned off.  It rarely happened for me so I never noticed the state was making it thru to HA and causing errors.

**Comment by thevoltagesource** [comment]
I have published a new release which addresses state = 3.  Please see the release notes and give it a try.

**Comment by kwkid** [comment]
Thx @thevoltagesource 
It's been coming up to 12 hours since i installed your latest version. Everything is looking good, seeing no errors in the Logs...
Consider this closed...
