### ISSUE TITLE
Doesn't seem to work when the unit is set to Celsius

### ISSUE THREAD

**Issue by otabay** [thevoltagesource/LennoxiComfort#37]
I have installed the component adding it manually to the configuration.yaml file, then I've added a thermostat card manually.
The preferences are set for metric (Celsius for temperature)
Temperatures shows up fine (21C), but when you attempt to change the temperature it starts jumping around randomly with values of -10C. It happens when you edit it from the card or if you go into the card's settings and you try to change the values from there as well.

**Comment by thevoltagesource** [comment]
Apologies for the late reply.  The underlying api is set to request and use the temperature units used by the thermostat and report those to HA, HA in turn should either use those units or convert them on the fly to the units defined in your HA preferences.  If this is still a problem for you, you can force the api to use specific units.  You will have to edit the file but it is fairly simple.  The file is located here:

`<HA Config>/custom_components/myicomfort/climate.py`

At or near line 152 of the file is this line:

`tstat = Tstat(username, password, system, zone, service)`

To force the API to use Celsius, add `,1` or `,0` to force it to Fahrenheit. The edited line should look look like this:

`tstat = Tstat(username, password, system, zone, service ,1)`

Let me know if this helps, or if this is not still an issue.

Jacob
