### ISSUE TITLE
Lennox Certificate Expired

### ISSUE THREAD

**Issue by kwkid** [thevoltagesource/LennoxiComfort#40]
Starting today to see this error in HA...

File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='services.myicomfort.com', port=443): Max retries exceeded with url: /DBAcessService.svc/GetSystemsInfo?UserId=xxxx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
During handling of the above exception, another exception occurred:

tried removing the custom component, rebooting and re-installing thinking it would solve the issue but the problem remains...

any suggestions ?

**Comment by CharlesGodwin** [comment]
I have the same problem. Started around 1300 Eastern Time 22/04/27

**Comment by kwkid** [comment]
My iOS iComfort app is also non responsive....it's been offline for 24 hours...Lennox website is silent...I hope Lennox did not decide to stop supporting the Wifi thermostat in favour of other more $$$ models they have

**Comment by kwkid** [comment]
I would agree too. Rebooted HA and it seems to be working. The iOS app is also responding...
Thx for confirming that you too had the issue Charles
