### ISSUE TITLE
Support unique_id

### ISSUE THREAD

**Issue by StephenGevers** [thevoltagesource/LennoxiComfort#41]
I'd like to be able to put my thermostats into an area, but the HA UI won't allow it because it doesn't have a unique_id and if I add a unique_id, I get invalid config

**Comment by thevoltagesource** [comment]
I have changed the code to present HA with a unique_id based on the system serial number and zone. Upgrade to release v3.3.0 and let me know if it is working for you.  There is no need to change the config.

**Comment by StephenGevers** [comment]
Working now...Thanks!
