### ISSUE TITLE
/config/custom_components/myicomfort/__init__.py blank ?

### ISSUE THREAD

**Issue by CCupler** [thevoltagesource/LennoxiComfort#43]
Installed LennoxiComfort via HACS. 
Created 'climate' entry in configuration.yaml as per the docs here. Added mycomfortsync username and password entries in secrets.yaml (again, per the docs, as I understood them.) 
I can't seem to "do" anything with the integration......  
Granted, I'm new to HA (just started on this a few weeks ago), and I don't write code, but....  the _init_.py for this integration is blank - noting there. Looking at other HCS integrations that I've installed (e.g. HACS, FordPass, Hubitat, or Remootio), those all have a init entry with, well, code in them - the iComfort init entry is entirely blank. 
Am I just dumb, and doing it wrong? Or, is this my issue?  
You need anything from me (feedback, logs (if you can point me to where to get them, it would help - again, HA noob here), please ask.

**Comment by CCupler** [comment]
Jacob, 
Thanks for the response. I updated my configuration.yaml as suggested. And.... I'm an idiot. I entered the wrong user name (I entered username-at-email, instead of username.) 
Fixed that, and, it's working. 

Again, thanks for the response. 

-Chris

**Comment by thevoltagesource** [comment]
Woot!  Glad you got it working.
