### ISSUE TITLE
Deprecated constants

### ISSUE THREAD

**Issue by stilldisturbing** [thevoltagesource/LennoxiComfort#44]
Home Assistant is deprecating the following constants as well as the support features values in HA Core 2025.1:

TEMP_CELSIUS (replaced with UnitOfTemperature.CELSIUS)
TEMP_FAHRENHEIT (replaced with UnitOfTemperature.FAHRENHEIT)

SUPPORT_TARGET_TEMPERATURE (replaced with ClimateEntityFeature.TARGET_TEMPERATURE)
SUPPORT_TARGET_TEMPERATURE_RANGE (replaced with ClimateEntityFeature.TARGET_TEMPERATURE_RANGE)
SUPPORT_PRESET_MODE (replaced with ClimateEntityFeature.PRESET_MODE)
SUPPORT_FAN_MODE (replaced with ClimateEntityFeature.FAN_MODE)
SUPPORT_AUX_HEAT (replaced with ClimateEntityFeature.AUX_HEAT)

https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by thevoltagesource** [comment]
Thanks for bringing this up and supplying the fix.  I appreciate the help.  PR #45 has been merged and release [v3.4.0](https://github.com/thevoltagesource/LennoxiComfort/releases/tag/v3.4.0) has been generated.
