### ISSUE TITLE
AirEase brand modification to api

### ISSUE THREAD

**Issue by bateschris** [thevoltagesource/LennoxiComfort#6]
I'm wondering if you'd consider a modification to the HA & python to account for an off-brand system?

I have an "AirEase" Heat Pump system, which is in every way the same as the Lennox, but the url for their api is "https://services.mycomfortsync.com/DBAcessService.svc/" instead. 

The only change I needed to make was to the python api.py @ line 35:
SERVICE_URL = "https://services.mycomfortsync.com/DBAcessService.svc/"
and everything works solidly. 

Seems like an if statement based on a config option would give ppl options for both. 

Regardless, thanks for all the work, I've been using it since we installed the system in January.

**Comment by thevoltagesource** [comment]
I think i can do this.  I have to re-write the integration to work with the climate redesign in 0.96 first and then I will get this going as well.

**Comment by thevoltagesource** [comment]
Integration and API have been updated to support this feature.  I know it works for Lennox, can you please confirm all is well on the AirEase side? This is built on top of the latest code so you will need to be running HA v0.96+

**Comment by bateschris** [comment]
I can confirm it works with the new AirEase settings as well. Had to
upgrade from 0.94 to 0.96.3 first, sorry for the delay in responding.
Thanks so much for your effort!
