### ISSUE TITLE
Directory change to add support for HACS

### ISSUE THREAD

**Issue by putz612** [thevoltagesource/LennoxiComfort#8]
A small change would be required to add this custom integration using the Home Assistant Community Store, the replacement for custom updater.  Would make it a bit easier to install and update. 

https://custom-components.github.io/hacs/developer/integration/

**Comment by thevoltagesource** [comment]
I think that is a great idea.  I heard about HACS on the podcast and wondered what it would take to get my code on there.  Thanks for the link.  I will add this to my weekend todo list.

**Comment by thevoltagesource** [comment]
This is finally complete.  I archived off all the old code, cleaned up the repository, made the folder change needed, added the HACS required files, created a pull request and as of this morning this integration is available thru HACS.  Tested it out on my system this afternoon and it works great.  Thanks for the suggestion!
